document.getElementById("header").innerHTML=`<a href="#">Google</a> <a href="#">Youtube</a> <a href="#">Spotify</a>`;
document.getElementById("main").innerHTML=`
<div>
<h3>Noticia 1</h3>
<p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rem deleniti eveniet quia quo laudantium mollitia ullam ducimus sequi aspernatur soluta.Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rem deleniti eveniet quia quo laudantium mollitia ullam ducimus sequi aspernatur soluta.Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rem deleniti eveniet quia quo laudantium mollitia ullam ducimus sequi aspernatur soluta.Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rem deleniti eveniet quia quo laudantium mollitia ullam ducimus sequi aspernatur soluta.</p>
<h3>Noticia 2</h3>
<p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rem deleniti eveniet quia quo laudantium mollitia ullam ducimus sequi aspernatur soluta.Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rem deleniti eveniet quia quo laudantium mollitia ullam ducimus sequi aspernatur soluta.Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rem deleniti eveniet quia quo laudantium mollitia ullam ducimus sequi aspernatur soluta.Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rem deleniti eveniet quia quo laudantium mollitia ullam ducimus sequi aspernatur soluta.</p>
<h3>Noticia 3</h3>
<p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rem deleniti eveniet quia quo laudantium mollitia ullam ducimus sequi aspernatur soluta.Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rem deleniti eveniet quia quo laudantium mollitia ullam ducimus sequi aspernatur soluta.Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rem deleniti eveniet quia quo laudantium mollitia ullam ducimus sequi aspernatur soluta.Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rem deleniti eveniet quia quo laudantium mollitia ullam ducimus sequi aspernatur soluta.</p>
</div>`;
document.getElementById("footer").innerHTML=`<a href="#main">Volver arriba</a>`;